### ISSUE TITLE
Adding own list of DGEs

### ISSUE THREAD

**Issue by wlason** [saeyslab/multinichenetr#102]
Thank you for an amazing package! 😀
I am currently working on a project in which we use a different method of DGE testing compared to what's implemented in MultiNicheNetR. I would like to use this method for the cell-cell interaction analysis for consistency. I wanted to ask how this can be achieved - what is the minimum set of columns I need to have in my `de_output_tidy` and do I have to test the contrast in both directions (e.g. `healthy-disease` and `disease-healthy`?

**Comment by browaeysrobin** [comment]
Hi @wlason 

If your current method of DGE testing is appropriate for multi-sample data, you can do this (so no regular FindMarkers, ...)
For each contrast / gene / cell type, you need a: logFC value, p-value, and adjusted p-value. You can test the contrast in one direction, but need both directions in the `de_output_tidy` table. To do so, you can create a table representing the opposite direction by multiplying logFC values with -1, and add this to the DE table you already have.
