### ISSUE TITLE
Are logcounts required in sce object?

### ISSUE THREAD

**Issue by catsargent** [saeyslab/multinichenetr#13]
Hi,

Please can you confirm whether the count data needs to be log normalized or not in the sce object? In step-by-step mode, when I run get_DE_info on my data it gives an error about not finding logcounts in the assay slot.

However, when I run the wrapper function on that same data, the DE analysis part works (it later fails when reaching the "Combine all the information in prioritization tables" section (I created an issue on github for this). I just wanted to check with you why the wrapper function does not fail if there are not logcounts in the assay slot. Are these somehow generated if using the wrapper script?

Thanks,
Catherine

**Comment by browaeysrobin** [comment]
Hi @catsargent 

Only raw counts are necessary if you run the DE analysis and wrapper with default parameters (`assay_oi_pb = counts`).

Can you provide your exact error message when running `get_DE_info` if you don't have a logcounts assay? On other datasets, this ran just fine with only the counts assay.

About the wrapper: one of the functions in the wrapper `get_abundance_expression_info` (and in the step-by-step vignette) will calculate logcounts in case they were absent.

**Comment by catsargent** [comment]
Hi,

Sorry for the delay in responding - I was on holiday.

This is the error I obtain when run get_DE_info using the step-wise approach and my object does not contain log normalized counts. But from your previous message, it sounds like I would need to have log normalized counts in the object and therefore the error would be expected?

Thanks,
Catherine

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'pairwiseTTests': 'assay(<SingleCellExperiment>, i="character", ...)' invalid subscript 'i'
'logcounts' not in names(assays(<SingleCellExperiment>))
```

**Comment by catsargent** [comment]
You're right - you had suggested using that option when troubleshooting the error in another issue (https://github.com/saeyslab/multinichenetr/issues/7) and I did not change it back. Thank you!
