### ISSUE TITLE
Error: not enough samples when there are

### ISSUE THREAD

**Issue by lo2811** [saeyslab/multinichenetr#17]
Hello,
Thank you for a great tool and detailed vignettes. I have a question related to the error: "not enough samples per group with sufficient cells of this cell type". I ran into this error with a cell type (CAFs) when I know for sure that there are enough cells, see below:
![Screenshot 2023-08-03 at 3 32 38 PM](https://github.com/saeyslab/multinichenetr/assets/12261634/2e4729f7-3b25-4005-9581-e5eb7b358587)

![Screenshot 2023-08-03 at 3 33 21 PM](https://github.com/saeyslab/multinichenetr/assets/12261634/c11499ab-707b-4b4e-b1eb-684bd196eaa7)

Do you know why this error showed up?

Thank you!

**Comment by browaeysrobin** [comment]
Hi @lo2811 

If I see it correctly: you have 3 groups with, after filtering out samples with insufficient CAFs (=L42572), 2 or more remaining samples per group. In theory, this should work, so let's try to find out the problem. 

Can you give me more details about how you ran the analysis?
Which vignette did you follow? Which function gives the error? What is the exact error message? What value of `min_cells` did you use? Did you assign batches or not? etc. The more information you provide, the more likely it is I will be able to help you.

**Comment by lo2811** [comment]
I reran the exact analysis without covariates and the error went away. So it has to do with using flowcell as a covariate, does multi_nichenet_analysis treat covariate and batch the same, i.e. each sample per batch/covariate should meet the min_cells parameter?

**Comment by browaeysrobin** [comment]
> I reran the exact analysis without covariates and the error went away. So it has to do with using flowcell as a covariate, does multi_nichenet_analysis treat covariate and batch the same, i.e. each sample per batch/covariate should meet the min_cells parameter?

Thanks for the information. Can you provide a table of sample_id vs flowcell so I can have insight in how your covariate is spread across the samples?

**Comment by browaeysrobin** [comment]
In any case, if your covariate is categorical, it will be considered the same as batch during the DE analysis, meaning that each leavel of the covariate should occur in at least one sample per group/condition. I improved the error message thrown in this function to make that clear. 

If this is the issue for your data, you can close this issue.
