### ISSUE TITLE
Error in UseMethod("inner_join")  when running make_lite_output

### ISSUE THREAD

**Issue by catsargent** [saeyslab/multinichenetr#21]
Hi,

when running my analysis using the step-wise approach, I encounter an error when running `multinichenet_output = make_lite_output(multinichenet_output)`

Error in UseMethod("inner_join") : 
  no applicable method for 'inner_join' applied to an object of class "NULL"

I had also had an error in the previous line of code where the function lr_target_prior_cor_inference is run. However, I was advised that this was due to having <5 samples in one of my groups (which is correct). Would this have anything to do with the above error? I therefore commented out the line where `lr_target_prior_cor` is added to `multinichenet_output`.

I know that the error does not impact the analysis but wanted to flag the issue. 
Thanks,
Catherine

**Comment by browaeysrobin** [comment]
This should be fixed now: `make_lite_output` will now assess whether `lr_target_prior_cor` is empty (when this could not be calculated because too few samples). 

Same issue as #24
