### ISSUE TITLE
contrast table for 4 groups

### ISSUE THREAD

**Issue by lw157** [saeyslab/multinichenetr#25]
Hi, 
I would like to make a contrast table for 4 groups, A, B, C, D. But I have trouble for the "group" in contrast_tbl.

```
contrasts_oi = c("'(C-D)-(A+B)','(C-A)+(D-B)'")
contrast_tbl = tibble(contrast =  c("(C-D)-(A+B)","(C-A)+(D-B)"),  group = c("C","C2"))
```

From the tutorial, the group must be chosen from A, B, C, D. Here I set group "C" for "(C-D)-(A+B)", but for (C-A)+(D-B), what should I set as C2 is not from ABCD.

Liuyang

**Comment by browaeysrobin** [comment]
Hi @lw157 

For the moment, I recommend running this in two separate analyses (so one analysis per contrast, each with "C" as group name).

**Comment by lw157** [comment]
> Hi @lw157
> 
> For the moment, I recommend running this in two separate analyses (so one analysis per contrast, each with "C" as group name).

Thanks a lot, Robin. I will run them separately with same group name.

Just one more question. I found the results (LR pairs) of "dividing by group number" is different from NOT dividing. In this case, should I divide by 2 or 4? e.g. ((C-D)-(A+B))/4 or (C-D)/2-(A+B)/2, or just go with (C-D)-(A+B) ?

Thanks again.

All best,
Liuyang

**Comment by lw157** [comment]
Thanks a lot, Robin. This is really helpful. I will close this post.
