### ISSUE TITLE
Setting multiple covariates and batches in multinichnet

### ISSUE THREAD

**Issue by iichelhadi** [saeyslab/multinichenetr#26]
as per title. Was wondering how to set multiple covariates and batches for batch correction?

Thank you

**Comment by browaeysrobin** [comment]
Multiple covariates: just make a vector of length > 1; should be find
Multiple batches: not possible, you can make a new column in the metadata combining your different batches.

**Comment by iichelhadi** [comment]
> 

thank you for the quick reply. I have integrated scRNA-seq datasets using harmony in a Seurat obj. I was thinking I should add "nCount_RNA", "nFeature_RNA" and "percent.mt" as covariates. I am not sure about the syntax I should be using.

something like this? c("nCount_RNA", "nFeature_RNA" , "percent.mt")
