### ISSUE TITLE
Nichenet v2 networks and matrices compatibility with nichenetr pipeline

### ISSUE THREAD

**Issue by ultimatex5** [saeyslab/multinichenetr#3]
Hi, 
first of all thank you for your work,
I was wondering if following your pipeline "step-by-step starting from a seurat object" (https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md) 
i could use the new "Nichenet v2 networks and matrices" that you included in the new multinichenetr (https://github.com/saeyslab/multinichenetr/blob/main/vignettes/detailed_analysis_steps_MISC.md).
So insted of download ligand_target_matrix, lr_network, weighted_networks from https://zenodo.org/record/3260758#.YlgI3S0QNQI i can use https://zenodo.org/record/5884439#.YlgI_i0QNQI.

I also note that all new files are bigger than the old ones with the exception of lr_network: lr_network.rds (old) is bigger than lr_network_human_21122021.rds (new).

**Comment by browaeysrobin** [comment]
Hi @ultimatex5 

Yes, you can also use the NicheNet v2 models in the normal NicheNet pipeline - just realize this is just a beta version and that for use in your publication(s) it is better to wait for our publication describing how we updated the NicheNet model and benchmarked it against the previous one. 
2 notes before you use it already: 1) the AUPR value is now a better metric than the pearson correlation for ligand activity prediction; 2) the new models come with updated gene symbols - the expression should thus also be in that format

The reason for size differences: lr_network contains now less predicted LR interactions, whereas data sources were added to the other networks
