### ISSUE TITLE
How to proceed when a cell type does not have enough number of cells in a group

### ISSUE THREAD

**Issue by anemartinezlarrinaga2898** [saeyslab/multinichenetr#31]
Hello!

Im running multinitchenet in a single cell object where I have three groups in different cell types. However when I run the 

`DE_info <-  get_DE_info(sce = sce, 
                        sample_id = sample_id, 
                        group_id = group_id, 
                        celltype_id = celltype_id, 
                        batches = batches, 
                        covariates = covariates, 
                        contrasts_oi = contrasts_oi, 
                        min_cells = min_cells,
                        findMarkers = TRUE)`

I get the following error: ""excluded cell types are:"

How should I proceed? Should this cell types be removed? What is the community doing or the library guys doing?

**Comment by browaeysrobin** [comment]
Hi @anemartinezlarrinaga2898 

the `"excluded cell types are:"` message is a warning message, not an error message. You can just continue the analysis. 

Note that we advise against using  `findMarkers = TRUE`. This option is more included for internal testing/comparisons and not for use by end users.
