### ISSUE TITLE
Interpretation of scaled ligand activity values

### ISSUE THREAD

**Issue by carolinemorrell** [saeyslab/multinichenetr#35]
Hi - thanks again for this great tool. 

A quick question about the scaled ligand activity value plots. 

I have one specific interaction (shown below - wnt5a -fzd6) which looks to be upregulated in my negative group on the absolute values, but then in the scaled value looks to have exactly the same values for up and down in both groups. I am not sure how to interpret this - are you able to shed any light?

Thanks

Caroline

![image](https://github.com/saeyslab/multinichenetr/assets/117285955/9d4ebfae-6fb3-4c62-9fc7-069129e2c268)

**Comment by browaeysrobin** [comment]
Hi @carolinemorrell 

You can read more about the interpretation in this issue: #33

Short answer: scaled activities represent the ranking of that ligand compared to other ligands in having target gene enrichment; unscaled values represent absolute enrichment. The higher the absolute enrichment, the more trustworthy, but we have encountered many situations with good ligand rankins (thus looking at scaled ligand activities) even though absolute enrichment was quite low.
