### ISSUE TITLE
Dissecting direct vs indirect effects of simulation

### ISSUE THREAD

**Issue by Git535323** [saeyslab/multinichenetr#36]
I have a mixed population of in vitro cells, stimulated with an exogenous stimulant. I would like to try to dissect the direct effects of simulation on cells vs. indirect (i e. due to intercellular signalling). 

With the current target correlation, I'm concerned that the predicted downstream targets of ligands seem to overlap with downstream targets of the exogenous simulation.

I wondered if you have considered this problem, and if so do you have any suggestions for how to approach it?

I thought about perhaps manually adding in the simulation as an upregulated ligand in each cell type, and then manually annotating the downstream effects to nichenet? Or, removing the known receptors for the simulation from the nichenet data?

**Comment by browaeysrobin** [comment]
Hi @Git535323 

This type of data is not the main target data we had in mind while developing MultiNicheNet and I recommend starting from the NicheNet framework (https://github.com/saeyslab/nichenetr) instead - it will provide more flexibility to properly define the geneset of interest based on which ligand activities are calculated. 

As you said, it is very important to get an idea about which genes are likely direct effects of the exogenous stimulation. These should then be removed from the DE genes of a cell type to get the "geneset of interest" which must only contain genes likely influenced by intercellular signaling. Whether this is reasonably possible or not, and how to do this, depends on your dataset (what stimulant you used etc). If you know which receptors are targeted by the stimulant, one option would be to look at the top target genes of the ligands binding that receptor according to the NicheNet database. In any case, this is not the ideal dataset for a NicheNet ligand activity analysis and I am not sure it's worth spending time on it.
