### ISSUE TITLE
Regarding Ligand-receptor DB

### ISSUE THREAD

**Issue by lagom2728** [saeyslab/multinichenetr#42]
Dear multinichenetr team,

Hello, thank you for developing a great algorithm. 
I am using your algorithm to analyze cell-cell interactions in different cancer types.   
In the meantime, I would like to ask you a question. 

I am doing research on finding binding partner ligand molecules for human receptor genes. 
The receptor genes I'm studying are largely unknown, although a few binding partners are known. 

However, according to the Ligand-receptor database provided by multinichnet, several genes that have not been reported in the literature are curated as binding partners of the receptor gene I am targeting. 

I have doubts about the reliability of this information because other similar databases, such as Cell chat and Cell phoneDB, do not have curated information. 

Is there any way to verify that the information about the curated gene pairs comes from a paper?
Or I would like to know on what evidence they curated that these genes interact with each other.

Thank you

**Comment by browaeysrobin** [comment]
Hi @lagom2728 

As mentioned in our preprint, we mainly combined two major resources: the Omnipath intercellular communication resource and this paper from Verschueren et al.: https://www.sciencedirect.com/science/article/pii/S0092867420306942?via%3Dihub.  The lr_network object provides information which of these was used for a specific interaction. In case the interaction comes from Omnipath, you can use the OmnipathR functionality to check the underlying databases/papers describing a certain interaction. (In the near-future v2 release of multinichenetr, we will integrate example code to connect with OmnipathR., but for now I suggest you try this yourself.)

If you would have strong doubts about specific interactions, you can mail them to me privately so we can check how they ended up in the database.
