### ISSUE TITLE
circos plot

### ISSUE THREAD

**Issue by inbarsh2** [saeyslab/multinichenetr#46]
Hi,
I have a question about the circos plot. In case I have sereval cell types with similar ligands and receptors (only the combination of sender-reciever is unique) I seem to not be able to create the circos plot unless I prioritize the cell type which will express it. Is there a way to have a circos plot with rpetitions of ligands or receptors?
Thank you,
inbar

**Comment by browaeysrobin** [comment]
Hi @inbarsh2 

You will have to come up with more detailed explanation, code and examples because we ourselves have no problems creating circos plots for repetitive ligand-receptor pairs.
