### ISSUE TITLE
How to visualize between sample differences in a group?

### ISSUE THREAD

**Issue by dhairya02** [saeyslab/multinichenetr#48]
Hi, is there a way to visualize sample differences in a group using the dot plot or any other plot? I was looking for a plot similar to the one we make for each group_oi using make_sample_lr_prod_activity_plots but highlighting differences between samples?

**Comment by browaeysrobin** [comment]
If there are differences between samples in ligand-receptor expression, then those will be visible on the plots you are talking about. 

For more insight into sample differences: MultiNicheNet is a tool focused on revealing differences between conditions, and not directly between individual samples.
