### ISSUE TITLE
How can I save the high resolution plots generated from multinichenetr with R code? 

### ISSUE THREAD

**Issue by kaarg2** [saeyslab/multinichenetr#50]
I'm running multinichenetr on a high computing cluster.I would like to save the plots generated from multinichenetr workflow with R codes instead of Rstudio interface. Is there a way I can save the plots non-interactively without showing the plots? Thank you.

**Comment by browaeysrobin** [comment]
Hi @kaarg2 

At the end of the readme in the section "Learning to use multinichenetr", you see a link to two scripts that we use.
One to run the analysis and calculations on a high computing cluster. One to read in the output and make visualizations locally.
