### ISSUE TITLE
Can't install multinichenetr on apple silicon macOS

### ISSUE THREAD

**Issue by kaarg2** [saeyslab/multinichenetr#51]
Multinichenetr can't be installed on apple silicon macOS. The following error prompts 
`Downloading GitHub repo saeyslab/multinichenetr@HEAD
── R CMD build ────────────────────────────────────────────────────────────────
─  building ‘multinichenetr_1.0.3.tar.gz’...
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘multinichenetr/vignettes/detailed_analysis_steps_empirical_pvalues_files/figure-gfm/unnamed-chunk-64-1.png’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wt/4f4m9q6s1vb0bb6v9ccjm5280000gn/T//RtmpYGyhSO/file9b1b613ac93b/multinichenetr_1.0.3.tar.gz’ had non-zero exit status`
I know there's no arm64 scran. Is there anyway to bypass this problem?

**Comment by browaeysrobin** [comment]
Hi @kaarg2 

Based on our most recent test (with Github Actions we test installation on Windows, MacOS, and Linux), and my own experience using macOS, there is no general problem in installing multinichenetr on macOS.

Without more information regarding your system, how you installed the package, and all the error messages thrown during installation (currently I only see warning messages in your post), we unfortunately cannot help you further.

**Comment by kaarg2** [comment]
Hello @browaeysrobin, my apologies for the omission. I am attempting to install MultiNicheNet on a apple silicon arm64 macOS Sonoma 14.2.1 in R 4.3.2. When I install multinichetr, the following are the only error message I receive, 
`── R CMD build ────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/wt/4f4m9q6s1vb0bb6v9ccjm5280000gn/T/RtmpVwCzkx/remotese42a6d117b6a/saeyslab-multinichenetr-3549fd8/DESCRIPTION’ ...
─  preparing ‘multinichenetr’:
─  building ‘multinichenetr_1.0.3.tar.gz’... preparing ‘multinichenetr’:
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘multinichenetr/vignettes/multifactorial_analysis_BreastCancer_files/figure-gfm/unnamed-chunk-35-1.png’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
system (cmd0): /Library/Frameworks/R.framework/Resources/bin/R CMD INSTALL
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wt/4f4m9q6s1vb0bb6v9ccjm5280000gn/T//RtmpVwCzkx/filee42a2e9f6866/multinichenetr_1.0.3.tar.gz’ had non-zero exit status`.
I installed the package using the following command, 
`devtools::install_github("saeyslab/multinichenetr",verbose=T)`.
I was able to install NicheNet successfully, but not MultiNicheNetR. I suspect it's a problem due to the SCRAN package on bioconductor which offers no support for arm64 architecture. 
scran has just released an arm64 architecture version on the bioconductor. After installing scran, the problem is resolved.
