### ISSUE TITLE
How to set "contrast_tbl" to reproduce Fig 3a

### ISSUE THREAD

**Issue by haotian-zhuang** [saeyslab/multinichenetr#57]
Dear Robin @browaeysrobin,

Thank you for the great tool. To reproduce the Fig 3a of the breast cancer example, I wonder how to set the "group" column in the "contrast_tbl"? The vignette uses the following setting, but is this the same setting to generate the Fig 3a? Thanks!

contrast_tbl = tibble(contrast =
                        c("(OnE-PreE)-(OnNE-PreNE)", "(OnNE-PreNE)-(OnE-PreE)"),
                      group = c("OnE","OnNE"))

**Comment by browaeysrobin** [comment]
hi @haotian-zhuang 

Yes, that was indeed the setting we used for the paper.

**Comment by haotian-zhuang** [comment]
Hi Robin @browaeysrobin,

Thank you for the prompt reply! Could you explain more why setting group = c("OnE","OnNE")) for Fig 3a? For example, why setting group = "OnNE" represents the "Interactions that increase during therapy in patients without expansion"?

And if keeping the "contrast" but setting group = c("OnE","PreE")), for example, how to interpret the two figures drawn?

Thanks!
