### ISSUE TITLE
Change font size in make_ligand_activity_target_plot()

### ISSUE THREAD

**Issue by AlexCHoppe** [saeyslab/multinichenetr#58]
Hello! I'v been using your multinichenetr and loving it - thank you! I used the pairwise comparison vignette first and that all worked fine, but now I'm trying the threewise comparison and my make_ligand_activity_target_plot() plot for one particular cell type has a lot of predicted genes - like ~200. 
Is there a way to either specify a limit to the predictions, or change the font size so they are clearer and not squashed on top of each other?
I tried to use ggplot: combine_plot + theme(text = element_text(size = 5)), but that returned 'NULL' so I'm guessing these plots don't work with ggplot.
I also tried to find the source code to see if I can change it there but I couldn't see anything.
Thanks heaps for your help and sorry if this is an annoying request!

**Comment by browaeysrobin** [comment]
Hi @AlexCHoppe 

There are several workarounds for this:
1) **- recommended -**  increasing the width of your output pdf/svg/png files of your plots will help visualize more target genes next to each other (the font size will automatically be smaller)
2) if you want to reduce the nr of genes shown, you can increase the stringency of the DE output parameters or decrease the top_n value before the ligand activity calculation.

If you want to see the source code of this plot, you can look here:https://github.com/saeyslab/multinichenetr/blob/main/R/plotting.R
