### ISSUE TITLE
Unable to install multinichenetr

### ISSUE THREAD

**Issue by Sphiltje** [saeyslab/multinichenetr#6]
Hi, 

I have been trying to install multinichenetr but it keeps giving me the same errors. This is the error message:

** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
Error: package or namespace load failed for 'multinichenetr':
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: library.dynam("Cairo", pkgname, libname)
  error: DLL 'Cairo' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
ERROR: loading failed for 'x64'
* removing 'C:/Users/sphiltje/Documents/R/win-library/4.0/multinichenetr'

I have already re-installed Cairo and I tried to use different versions of R. Nothing seems to work. My current R version is 4.0.4. I have also tried to install with the "dependencies=TRUE" option but this also didn't work. Is there anything that I can do to fix this issue?

Thanks!

**Comment by browaeysrobin** [comment]
Hi @Sphiltje 

Is it possible that you work on a Mac?

See also this issue from the nichenetr package: https://github.com/saeyslab/nichenetr/issues/155
