### ISSUE TITLE
incorporating ATAC-seq data?

### ISSUE THREAD

**Issue by wanghlv** [saeyslab/multinichenetr#60]
Hi I'm wondering if it's possible to incorporate the single cell ATAC-seq data? to further model on the "target" side in multi-condition/multi-sample dataset? Thanks a lot!

**Comment by browaeysrobin** [comment]
Hi @wanghlv 

Currently there is no support for this specifically for multi-sample datasets in MultiNicheNet. 
In the base NicheNet package (https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md) we provided a vignette where it is demonstrated how to generate your own ligand-target model. In theory, it is possible to use your scATAC-seq data to define a context-specific GRN, and thus context-specific ligand-target matrices in the end. Such a context-specific ligand-target matrix could then be used in MultiNicheNet.

**Comment by wanghlv** [comment]
Thank you for your suggestion, I will give a try!!
