### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nicolebussola** [saeyslab/multinichenetr#62]
Hi!

Thank you for this great tool, looking forward to the next release for condition-specific cell types! I am currently analyzing two datasets with the same condition and I am interested in finding reproducible signals. Thus, I am setting the weight for DE to 0 as I am looking for similarities and not differences; I am not sure on how to deal with ligand activity as it considers genesets output by the DE analysis. Can I weight the L-R pairs to have a high activity based on target genes that are not DE? Do you have any other suggestions I should keep in mind?

Thanks
Nicole

**Comment by browaeysrobin** [comment]
Hi @nicolebussola 

MultiNicheNet has been designed to specifically analyze _differential_ cell-cell communication patterns. Every part of the algorithms serves to prioritize which signals are different between your conditions. Therefore, I recommend against using MultiNicheNet for your application (and I will close this issue). I suggest you try out classic CCC tools on each of your datasets, and look at the intersection of the top results there.
