### ISSUE TITLE
min_cells Contradictory Default

### ISSUE THREAD

**Issue by DarioS** [saeyslab/multinichenetr#66]
Documentation states that there is default value.

```
min_cells: Indicates the minimal number of cells that a sample should
           have to be considered in the DE analysis. Default: 10.
```

Code execution shows the opposite.

```r
Error in `dplyr::mutate()`:
 In argument: `keep = n >= min_cells`.
 In group 1: `sample_id = "HN118_P"` and `celltype_id = "Tumor"`.
Caused by error:
! argument "min_cells" is missing, with no default
```

**Comment by browaeysrobin** [comment]
Hi @DarioS 

Thank you very much for pointing this out. There were indeed a couple of functions where the default was not set up properly. This should be fixed now in the version on the dev-branch (which will be merged with the main branch this week).
