### ISSUE TITLE
'combine_sender_receiver_de' function exists in nichenetr and multinichenetr 

### ISSUE THREAD

**Issue by avpatel18** [saeyslab/multinichenetr#70]
This function takes different arguments so it gives 'unused arguments' error. I think you might want to rename and update tutorials. Thanks!

**Comment by Chenium123** [comment]
Same

**Comment by Chenium123** [comment]
> Same

After retrying, there were no errors. It is likely due to updating the NicheNet version (2.1.4 → 2.1.5). I suggest updating and then trying again.

**Comment by browaeysrobin** [comment]
If you apply _multinichenetr_ as described in the vignettes, there is no problem with this. Feel free to open an issue in the nichenetr package if there would be issues there.
