### ISSUE TITLE
Issue with group_prioritization_table being empty

### ISSUE THREAD

**Issue by NeuralBind** [saeyslab/multinichenetr#71]
Hello, 

I am trying to set up the tool following the vignettes, and i have 2 questions regarding the outputs and inputs.

I try to look at disease progression between 3 time points condition 1 , 2, 3. I have already SCT normilized data, but im not sure if it requires normilized or raw counts. Different vignettes seem to handle it differently even with similar comparisons.
What would be the best way to look from 1 to 2 and 2 to 3 because from the vignettes for a single comparison is going ex.1-2, 2-1.  Should i run 2 different pairwise analyses or could i include them in a single one?

Thank you for this amazing tool!

**Comment by browaeysrobin** [comment]
Hi @NeuralBind 

You should always start from raw counts. Can you please provide us with the vignettes that state you need normalized counts? Normally every vignette should start from raw counts, which is also mentioned in the Readme.

For the 3 time-point comparison; 

- if you are interested in specific interactions per time point; I suggest you base yourself on the 3-condition vignettes (MIS-C case study, like in the start tutorial). 
- if you are interested in increases over time between consecutive time points, I recommend these contrasts: t2-vs-t1 and t3-vs-t2. 

Of course, you can apply both approaches.

**Comment by NeuralBind** [comment]
Hi @browaeysrobin ,

In the specific [vignette](https://github.com/saeyslab/multinichenetr/blob/main/vignettes/basic_analysis_steps_MISC_SACL.knit.md) , the dataset is normilized before.  Also in my case i have the SCT assay with the corrected umi counts, but it yields different results than using the RNA (raw) counts.
Thank you for the experiment setup input.
