### ISSUE TITLE
Error in Interpretable bubble plots

### ISSUE THREAD

**Issue by Chenium123** [saeyslab/multinichenetr#72]
I encountered the following error while generating interpretable bubble plots:
> plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
+   multinichenet_output$prioritization_tables, 
+   prioritized_tbl_oi_M_50 %>% inner_join(lr_network)
+ )
Joining with `by = join_by(ligand, receptor)`
Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "NULL"

Two weeks ago, I had no issues running the same code and using the same output files. I haven’t updated your package during this period, which makes me very puzzled.

![image](https://github.com/saeyslab/multinichenetr/assets/60773031/2484a90d-47ef-41f0-b9e7-8a97d6c73387)
![image](https://github.com/saeyslab/multinichenetr/assets/60773031/67c4555a-238a-4746-81b7-0a68fe63790a)
![image](https://github.com/saeyslab/multinichenetr/assets/60773031/064b017a-1a1e-4369-885b-443806c72c36)

**Comment by maartenciers** [comment]
Can you make sure the variables `ligand` and `receptor` aren't NULL or empty? You can do this with `is.null(ligand)` or `is.null(receptor)`

**Comment by Chenium123** [comment]
> Can you make sure the variables `ligand` and `receptor` aren't NULL or empty? You can do this with `is.null(ligand)` or `is.null(receptor)`.

I have just made sure they are all not NULL. If you have recently been using this package, you can try running this step in your environment. I have contacted several friends, and they all encountered the same error and issue. It seems to have appeared only recently.

**Comment by maartenciers** [comment]
The function comes from the nichenetr package can you make sure to also install and load the nichenetr package using `library(nichenetr)` or with `nichenetr::convert_alias_to_symbols(ligand, organism = organism)`? This should resolve the error you encounter.

**Comment by maartenciers** [comment]
Additionally, make sure you read each step in the vignettes thoroughly, especially read [this](https://github.com/saeyslab/multinichenetr/blob/main/vignettes/basic_analysis_steps_MISC.knit.md) as it gives a detailed explanation on all steps needed to run multinichenetr. Following packages are needed for the analysis:
```
library(SingleCellExperiment)
library(dplyr)
library(ggplot2)
library(nichenetr)
library(multinichenetr)
```

**Comment by Chenium123** [comment]
After comparing the parameters with the source code, I found that the issue arises from some parameters in the new visualization code being incompatible with the multinichenet output file generated by version 1.0.3. It is necessary to run the full version 2.0.0 program. However, while running version 2.0.0, I encountered an issue consistent with issue #70. The developer needs to fix this. Thank you!

**Comment by browaeysrobin** [comment]
Hi @Chenium123 
The issue is indeed this: Some visualization options of multinichenetr version >= 2.0.0. are only compatible with MultiNicheNet output object generated by version multinichenetr version >= 2.0.0. 
This is now added to the Readme of this package.
