### ISSUE TITLE
Older version

### ISSUE THREAD

**Issue by shelby2919** [saeyslab/multinichenetr#76]
Hello, 

I have a prior analysis that I need to revisit, but I am having trouble finding a way to load multinichenet v1.0.3. Is there a way I can load this version to RStudio?

**Comment by browaeysrobin** [comment]
Hi @shelby2919 

I would recommend using the v2 version.

However, if that would really not be an option: you can install the v1.0.3. version by running
`remotes::install_github("saeyslab/multinichenetr@411e2a7")`
