### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sidrahmaryam-cyber** [saeyslab/multinichenetr#77]
Hello,
I updated my R and RStudio to latest version, and now when I am trying to install multinichenetr, I am getting this error. 

Downloading GitHub repo saeyslab/multinichenetr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/saeyslab/multinichenetr/tarball/HEAD' failed

Can you please let me know the possible issue with this. Thanks

**Comment by sidrahmaryam-cyber** [comment]
I could somehow work this one out, by trying again and again. 
However, While running multinichnet, I am getting this error. 


plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
+   multinichenet_output$prioritization_tables, 
+   prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all)
+ )
Joining with `by = join_by(ligand, receptor)`
Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "NULL"


Can you please help in this case.

**Comment by browaeysrobin** [comment]
> I could somehow work this one out, by trying again and again. However, While running multinichnet, I am getting this error.
> 
> plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
> 
> * multinichenet_output$prioritization_tables,
> * prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all)
> * )
>   Joining with `by = join_by(ligand, receptor)`
>   Error in UseMethod("mutate") :
>   no applicable method for 'mutate' applied to an object of class "NULL"
> 
> Can you please help in this case.

Can you check whether 

1) multinichenet_output$prioritization_tables is not empty
2) prioritized_tbl_oi_M_50 is not empty
3) lr_network_all s not empty
4) prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all)

Normally none of these elements should be empty, but I guess they are in your case here (I will assume this error occurs on your data, not on the vignette data). Possible reasons: problems reading in the lr_network, wrong definition of condition_oi, or senders_oi/receivers_oi, leading to an empty prioritized_tbl_oi_M_50. By looking into these, you should be able to identify where things went wrong.

**Comment by browaeysrobin** [comment]
Because the main issue you reported is not a MultiNicheNet issue, I will close this issue. Feel free to open a new issue with your other problem. This helps other users find back relevant issues better.
