### ISSUE TITLE
multi_nichenet_analysis Requires Writing All Combinations of Contrasts

### ISSUE THREAD

**Issue by DarioS** [saeyslab/multinichenetr#78]
It should not be necessary to manually write all of the contrasts for the convenience wrapper function.

> Perform a MultiNicheNet analysis in an all-vs-all setting.

`contrasts_oi` and `contrast_tbl` could be automatically generated based on factor levels. Also, since most people will be analysing human data, why is there no default value for `lr_network`? Ideally, `lr_network = "human"` would seamlessly fetch it from Zenodo.

**Comment by maartenciers** [comment]
> It should not be necessary to manually write all of the contrasts for the convenience wrapper function.

In theory, it is possible to generate contrasts automatically based on factor levels, depending on the design complexity. However, the main drawback is that the output will heavily depend on the specific contrasts set, which directly impacts the biological question you are addressing. Automating this process would overlook the importance of carefully considering the questions you are trying to solve. Depending on the biological question, the appropriate contrasts can vary significantly, as not every experiment is designed simply to compare treated versus untreated conditions. MultiNicheNet was designed to tackle complex experimental designs. Therefore, it is crucial to manually define contrasts to ensure they align with your research goals. That said, out of curiosity, how would you automate it in such a way to handle more complex designs and easy to understand?

**Comment by DarioS** [comment]
Ah, it would not be suitable for more complex designs.
