### ISSUE TITLE
conditions written in contrasts_oi should be in the contrast column of contrast_tbl column! 

### ISSUE THREAD

**Issue by Dalhte** [saeyslab/multinichenetr#82]
Hello again
I think it's very basic but I can't figure it by myself :/
I have a seurat object with 4 conditions integrated (namely, D2, PM, PS and E) each condition has only one sample (yeah we are poor !). From what I can understand, in my case, sample_id and group_id are confounded (and are the infamous "orig.ident"). I want to compare only two conditions to begin with, let's say PM and PS
So I did : 
sce = Seurat::as.SingleCellExperiment(integrated, assay = "SoupXRNA")
sce = alias_to_symbol_SCE(sce, "mouse") %>% makenames_SCE()

sample_id = "orig.ident"
group_id = "orig.ident"
celltype_id = "cell_Type"
covariates = NA
batches = NA

contrasts_oi = c("'PM-PS'") 
contrasts_oi 
contrast_tbl = tibble(contrast = 
                        c("'PM-PS'"), 
                      group = c("PM","PS"))

senders_oi = SummarizedExperiment::colData(sce1)[,celltype_id] %>% unique()
receivers_oi = SummarizedExperiment::colData(sce1)[,celltype_id] %>% unique()
sce1 = sce1[, SummarizedExperiment::colData(sce1)[,celltype_id] %in% 
            c(senders_oi, receivers_oi)
]

conditions_keep = c("PM","PS")
sce1 = sce1[, SummarizedExperiment::colData(sce1)[,group_id] %in% 
            conditions_keep
]

#Defining parameters for the MultiNicheNet wrapper function
min_cells = 10
min_sample_prop = 0.50
fraction_cutoff = 0.05
empirical_pval = FALSE
logFC_threshold = 0.50
p_val_threshold = 0.05
p_val_adj = FALSE 
top_n_target = 250
n.cores = 8
scenario = "regular"
ligand_activity_down = FALSE

multinichenet_output = multi_nichenet_analysis(
  sce = sce, 
  celltype_id = celltype_id, sample_id = sample_id, group_id = group_id, 
  batches = batches, covariates = covariates, 
  lr_network = lr_network, ligand_target_matrix = ligand_target_matrix, 
  contrasts_oi = contrasts_oi, contrast_tbl = contrast_tbl, 
  senders_oi = senders_oi, receivers_oi = receivers_oi,
  min_cells = min_cells, 
  fraction_cutoff = fraction_cutoff, 
  min_sample_prop = min_sample_prop,
  scenario = scenario, 
  ligand_activity_down = ligand_activity_down,
  logFC_threshold = logFC_threshold, 
  p_val_threshold = p_val_threshold, 
  p_val_adj = p_val_adj, 
  empirical_pval = empirical_pval, 
  top_n_target = top_n_target, 
  n.cores = n.cores, 
  verbose = TRUE
)

And I get : 
Erreur dans multi_nichenet_analysis(sce = sce1, celltype_id = celltype_id,  : 
  conditions written in contrasts_oi should be in the contrast column of contrast_tbl column! This is not the case, which can lead to errors downstream.
However : 
> contrasts_oi 
[1] "'PM-PS'"
> contrast_tbl
# A tibble: 2 × 2
  contrast group
  <chr>    <chr>
1 'PM-PS'  PM   
2 'PM-PS'  PS   
Seems ok to me :/
Can you help me ?
Best 
David

PS, I try with the demo
sce = readRDS(url( "https://zenodo.org/record/8010790/files/sce_subset_misc.rds")

And it work beautifully !

**Comment by Dalhte** [comment]
okay, once again I found my problem. Sorry about that, I think sending you message is part of the process. 
contrast_tbl = tibble(contrast =
c("'PM-PS'"),
group = c("PM","PS"))
should be
contrast_tbl = tibble(contrast =
c("PM-PS"),
group = c("PM","PS"))
Subtil but yet essential :p

but I have a new problem now : 
Same script as before. My cluster ID are 
[1] "Make diagnostic abundance plots + define expressed genes"
Joining with `by = join_by(sample_id, group_id, celltype_id)`
[1] "condition-specific celltypes:"
character(0)
[1] "absent celltypes:"
 [1] Cluster_S   Cluster_L   Cluster_FSC Cluster_C   Cluster_Le  Cluster_EC  Cluster_G   Cluster_M   Cluster_T   Cluster_Pe 
Levels: Cluster_S Cluster_L Cluster_FSC Cluster_C Cluster_Le Cluster_EC Cluster_G Cluster_M Cluster_T Cluster_Pe
Error in `dplyr::filter()`:
ℹ In argument: `is.na(fraction_sample)`.
Caused by error:
! objet 'fraction_sample' introuvable
Run `rlang::last_trace()` to see where the error occurred.
  1. ├─multinichenetr::multi_nichenet_analysis(...)
  2. │ └─multinichenetr::get_frac_exprs(...)
  3. │   ├─base::nrow(frq_df %>% dplyr::filter(is.na(fraction_sample)))
  4. │   └─frq_df %>% dplyr::filter(is.na(fraction_sample))
  5. ├─dplyr::filter(., is.na(fraction_sample))
  6. ├─dplyr:::filter.data.frame(., is.na(fraction_sample))
  7. │ └─dplyr:::filter_rows(.data, dots, by)
  8. │   └─dplyr:::filter_eval(...)
  9. │     ├─base::withCallingHandlers(...)
 10. │     └─mask$eval_all_filter(dots, env_filter)
 11. │       └─dplyr (local) eval()
 12. └─base::.handleSimpleError(...)
 13.   └─dplyr (local) h(simpleError(msg, call))
 14.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)

Can you help ?
Best 
David

**Comment by Shi-YuZhang** [comment]
Hi @Dalhte I met the same error 'Error in `dplyr::filter()`:
ℹ In argument: `is.na(fraction_sample)`.'

when executing ```Error in `dplyr::filter()`:
ℹ In argument: `is.na(fraction_sample)`.```
Can you tell me how you solved it？

**Comment by Dalhte** [comment]
Hi @Shi-YuZhang 
I'm really sorry but I cannot remember. I tried so much different things.
All I remember is that checking every intermediate object generated help me to pinpoint the steps that were not working
The program is very sensitive to min-cells, min_sample_prop, fraction_cutoff parameters (if you set those to low to conserve rare cell clusters, in my hands, it generate errors)
I also had to replace every filter by dplyr::filter because of package conflict 
It's handmade patching but I'm not a bioinformatician :) 
Best
David
