### ISSUE TITLE
Receiver cells in differential analysis

### ISSUE THREAD

**Issue by Cacti-Jiang** [saeyslab/multinichenetr#86]
Hi,
I am wondering how to select receiver cells in the differential cell-cell interaction analysis. Specifically, when considering the differentially interactions between two conditions (Condition A vs Condition B) that induce cell type transition (from progenitor to differentiated cells), where the differentiation genes act as target genes. Should we use (progenitor+differentiated cell) or (progenitor in Condition A+differentiated cell in Condition B) or (progenitor in Condition A + progenitor in Condition B) as receiver cells?

**Comment by browaeysrobin** [comment]
Hi @Cacti-Jiang 

In that scenario, I would combine (progenitor+differentiated cell) into one annotation as receiver cells for MultiNicheNet.

I would also suggest looking at the the base NicheNet package (https://github.com/saeyslab/nichenetr), since it could offer more flexibility.

**Comment by Cacti-Jiang** [comment]
Thanks a lot, that really helped!
