### ISSUE TITLE
Defining a confident set of upregulated interactions per group

### ISSUE THREAD

**Issue by Git535323** [saeyslab/multinichenetr#98]
Hi, I'm extracting predicted upregulated LR interactions from MNN analysis to construct graphs/networks that can be statistically compared between groups. E.g. comparing the network of upregulated interactions from group A vs. C, to those upregulated in B vs. C.

The method for defining a set of LR interactions per group has been either to take the top N, or using a threshold for prioritization score. However, there seems to be some bias introduced when trying to compare between groups using this method (particularly when looking at a larger number of interactions, rather than say the top 25 per group).

Do you have any suggestions for extracting this kind of information from MNN results?

**Comment by DarioS** [comment]
Would the software developer consider adding [Fisher's method](https://en.wikipedia.org/wiki/Fisher%27s_method) of combining p-values for an overall p-value per pair?

**Comment by Git535323** [comment]
Yes something like in CellChat, where they give a probability per interaction per cell-cell pair could be very useful.

**Comment by browaeysrobin** [comment]
Hi @Git535323 

What do you exactly want to compare between groups? If you choose a top n, you will already compare between groups, and groups with more interaction will have more interactions in the final plots.

We will not calculate a probability per interaction / per cell-cell pair. The main reason is that we don't want to give false confidence to users that a certain interaction is "significant" or has a certain probability score that could be interpreted as a strict statistical probability. The only thing we want to do is the ranking of interactions based on criteria that we think are informative for cell-cell communication. The better the rank of an interactions, the more information we have to say this interaction may be relevant in the condition of interest. That's the only message MultiNicheNet aims to bring. We don't think there is sufficient information in transcriptomics data to make statements about true probability of interactions, and therefore we don't want to calculate probability scores that could be misinterpreted that way. 

Alternatively, you could calculate the number of prioritized LR interactions between any cell type pair in the top n of total interactions (n=500 or 1000 could work) . This may be a useful metric to indicate which cell types could be interacting, but this has quite some limitations.
